name: build

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for updates and push
      run: |
        git clone -b master https://github.com/double-beep/SmokeDetector sd_clone
        cd sd_clone
        git pull https://github.com/Charcoal-SE/SmokeDetector master
        git push
